name: Github action PoC to build any Otel Collector from a manifest
inputs:
  local_manifest:
    description: Local manifest file path
    required: true
  local_output_path:
    description: Local path to put the generated files into
    required: true

runs:
  using: docker
  image: Dockerfile
